language: csharp
solution: Amaury.sln
mono: none
dotnet: 2.1.301
env:
  - PACKAGE_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
script:
 - dotnet restore
 - dotnet build
 - dotnet pack --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
