dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: Amaury.sln
mono: none
env:
  - PACKAGE_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
services:
  - docker
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - dotnet restore
 - dotnet build
 - docker run --name dynamo -d -p 8000:8000 -e AWS_ACCESS_KEY_ID='root' -e AWS_SECRET_ACCESS_KEY='secret' amazon/dynamodb-local
 - sleep 10
 - dotnet test
 - dotnet pack --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
