dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: Amaury.sln
mono: none
env:
  - PACKAGE_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
script:
 - dotnet restore
 - dotnet build
 - dotnet pack --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
