dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: Amaury.sln
mono: none
env:
  - PACKAGE_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:8000:8000 -e AWS_ACCESS_KEY_ID=root -e AWS_SECRET_ACCESS_KEY=secret amazon/dynamodb-local
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - dotnet restore
 - dotnet build
 - dotnet pack --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
