dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: Amaury.sln
mono: none
env:
  - PACKAGE_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
  - API_KEY="123123"
services:
  - docker
before_install:
 - docker run -d -p 8000:8000 -e AWS_ACCESS_KEY_ID='root' -e AWS_SECRET_ACCESS_KEY='secret' amazon/dynamodb-local
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - dotnet restore
 - dotnet build -c Release
 - dotnet test
 - dotnet pack -c Release --no-restore --no-build --include-symbols /p:PackageVersion=$PACKAGE_VERSION
 - dotnet nuget push /home/travis/build/tiagorosendo/amaury/src/Amaury/bin/Release/Amaury.$PACKAGE_VERSION.nupkg -k $API_KEY
 
